### ISSUE TITLE
Delete object in some cases fails with error "error reading from server: EOF"

### ISSUE THREAD

**Issue by vdomnich-yadro** [nspcc-dev/neofs-s3-gw#649]
## Steps to Reproduce (for bugs)
In most cases object deletion works correctly. However, when we delete object with tags via boto3 we are getting internal error. The same test via aws cli works correctly.

The steps were:
* Create a new S3 bucket and enable tagging in it
* Put object into the bucket
* Put object tags and get object tags
* Put object tags and get object tags (again)
* Delete object tags
* Delete object from the bucket

## Expected Behavior
The object is deleted.

## Current Behavior
The request fails with error (timestamp 16:10:50 in the attached [test-log](https://github.com/nspcc-dev/neofs-s3-gw/files/9270667/test-log-eof.txt)):
```
<?xml version="1.0" encoding="UTF-8"?>
  <DeleteResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Error>
      <Code>BadRequest</Code>
      <Message>mark object removal via connection pool: remove object via client: delete object on client: status: code = 1024 message = incomplete object PUT by placement: could not close object stream: (*putsvc.remoteTarget) could not put object to [/dns4/node4.neofs/tcp/8080]: write object via client: close RPC: rpc error: code = Unavailable desc = error reading from server: EOF</Message>
      <Key>0fdf9f99-6158-4b70-a14a-04526fb6f82f</Key>
    </Error>
</DeleteResult>
```

## Your Environment
4 cloud VMs with 4 storage nodes and 4 s3 gateways.
The issue reproduces both when s3 gateway has 1 peer and 4 peers.

* Version used:
v0.30.2

**Comment by vdomnich-yadro** [comment]
The same error was also observed in previous version of the system (v0.30.0+), where it was occurring in sporadic fashion.

**Comment by KirillovDenis** [comment]
It seems the reason is a panic in node: https://github.com/nspcc-dev/neofs-node/issues/1664

When it happens:
```
авг 08 19:36:30 buky neofs-node[895]: panic: runtime error: index out of range [0] with length 0
авг 08 19:36:30 buky neofs-node[895]: goroutine 185191 [running]:
авг 08 19:36:30 buky neofs-node[895]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/writecache.(*cache).Delete(0xc000395320, {{0x1e, 0xf8, 0xbd, 0xfa, 0x8, 0x54, 0x2e, 0xfd, 0x3d, ...}, ...})
авг 08 19:36:30 buky neofs-node[895]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/writecache/delete.go:31 +0xeaf
....
```
other nodes get `connection refused`:
```
авг 08 19:36:32 glagoli neofs-node[371]: 2022-08-08T19:36:32.635Z        error        policer/check.go:137        receive object header to check policy compliance        {"component": "Object Policer", "object": "5fq3NSoYKPrYfFVjkWd8gBbjYnDVXNLZHZVh7oDkCsth/6XuaRC49x61mqK7EQngLV2wof2i8GaUYjbTVU15q15Ps", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/node2.neofs/tcp/8080]: read object header from NeoFS: write request: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.26.161.153:8080: connect: connection refused\""}
авг 08 19:36:35 glagoli neofs-node[371]: 2022-08-08T19:36:35.638Z        error        policer/check.go:137        receive object header to check policy compliance        {"component": "Object Policer", "object": "F2kjLrXXyoFwEEkz2nLpZ7jLk9LrM6wEvZSgN5yC77k8/6XjicxLPaREaE6aAkKGWHJWJWy9gPBmnPvyxMLb3t9CA", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/node2.neofs/tcp/8080]: read object header from NeoFS: write request: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.26.161.153:8080: connect: connection refused\""}
```
which results in failed object removal.

We should wait for https://github.com/nspcc-dev/neofs-node/pull/1672 and see if things get better.

**Comment by alexvanin** [comment]
@vdomnich-yadro Is it reproduced on nightly builds from master branch?
