### ISSUE TITLE
Runtime panic at checksum hash

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-s3-gw#741]
Seems like request was interrupted, but still panic is not something we are expecting to see.

```
Nov 07 14:08:05 az neofs-s3-gw[55804]: 2022-11-07T14:08:05.389Z        error        handler/util.go:29        call method        {"status": 500, "request_id": "bed3aeee-ddaf-4ae0-bb65-fd771033775e", "method": "PutObject", "bucket": "d9d604f3-f44b-4082-bac1-c933569aaa97", "object": "a3e1d7c7-2b6e-470c-a789-66cdb8201094", "description": "could not upload object", "error": "save object via connection pool: init call context: no healthy client", "body close errors": []}
Nov 07 14:08:05 az neofs-s3-gw[55804]: 2022-11-07T14:08:05.391Z        info        http/server.go:3195        http: panic serving 10.78.69.101:56060: d.nx != 0
Nov 07 14:08:05 az neofs-s3-gw[55804]: goroutine 2940085 [running]:
Nov 07 14:08:05 az neofs-s3-gw[55804]: net/http.(*conn).serve.func1()
Nov 07 14:08:05 az neofs-s3-gw[55804]:         net/http/server.go:1825 +0xbf
Nov 07 14:08:05 az neofs-s3-gw[55804]: panic({0xea4ea0, 0x131ce10})
Nov 07 14:08:05 az neofs-s3-gw[55804]:         runtime/panic.go:844 +0x258
Nov 07 14:08:05 az neofs-s3-gw[55804]: crypto/sha256.(*digest).checkSum(0xc000ac67a8)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         crypto/sha256/sha256.go:234 +0x192
Nov 07 14:08:05 az neofs-s3-gw[55804]: crypto/sha256.(*digest).Sum(0xc006af8bb0?, {0x0, 0x0, 0x0})
Nov 07 14:08:05 az neofs-s3-gw[55804]:         crypto/sha256/sha256.go:210 +0x7d
Nov 07 14:08:05 az neofs-s3-gw[55804]: github.com/nspcc-dev/neofs-s3-gw/api/layer.(*layer).objectPutAndHash(0xc001d35620, {0x132cd28, 0xc054a03320}, {{0xc006af8bb0, 0x0}, {0xee, 0xe2, 0xae, 0xb9, 0x92, ...}, ...}, ...)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         github.com/nspcc-dev/neofs-s3-gw/api/layer/object.go:409 +0x1cc
Nov 07 14:08:05 az neofs-s3-gw[55804]: github.com/nspcc-dev/neofs-s3-gw/api/layer.(*layer).PutObject(0xc001d35620, {0x132cd28, 0xc054a03320}, 0xc054e821e0)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         github.com/nspcc-dev/neofs-s3-gw/api/layer/object.go:246 +0x953
Nov 07 14:08:05 az neofs-s3-gw[55804]: github.com/nspcc-dev/neofs-s3-gw/api/handler.(*handler).PutObjectHandler(0xc001d62d20, {0x132b740, 0xc028ac5980}, 0xc054a39200)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         github.com/nspcc-dev/neofs-s3-gw/api/handler/put.go:249 +0x63b
Nov 07 14:08:05 az neofs-s3-gw[55804]: net/http.HandlerFunc.ServeHTTP(...)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         net/http/server.go:2084
Nov 07 14:08:05 az neofs-s3-gw[55804]: github.com/nspcc-dev/neofs-s3-gw/api/metrics.APIStats.func1({0x132b710?, 0xc0549334a0}, 0xc054a39200)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         github.com/nspcc-dev/neofs-s3-gw/api/metrics/api.go:122 +0x26e
Nov 07 14:08:05 az neofs-s3-gw[55804]: net/http.HandlerFunc.ServeHTTP(...)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         net/http/server.go:2084
Nov 07 14:08:05 az neofs-s3-gw[55804]: github.com/nspcc-dev/neofs-s3-gw/api.(*maxClients).Handle.func1({0x132b710, 0xc0549334a0}, 0xc054a39200)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         github.com/nspcc-dev/neofs-s3-gw/api/max_clients.go:51 +0x2fe
Nov 07 14:08:05 az neofs-s3-gw[55804]: net/http.HandlerFunc.ServeHTTP(0xc001d62d20?, {0x132b710?, 0xc0549334a0?}, 0xc054a39200?)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         net/http/server.go:2084 +0x2f
Nov 07 14:08:05 az neofs-s3-gw[55804]: github.com/nspcc-dev/neofs-s3-gw/api.appendCORS.func1.1({0x132b710, 0xc0549334a0}, 0xc000ac7560?)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         github.com/nspcc-dev/neofs-s3-gw/api/router.go:143 +0x6e
Nov 07 14:08:05 az neofs-s3-gw[55804]: net/http.HandlerFunc.ServeHTTP(0xfff880?, {0x132b710?, 0xc0549334a0?}, 0xc054177020?)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         net/http/server.go:2084 +0x2f
Nov 07 14:08:05 az neofs-s3-gw[55804]: github.com/nspcc-dev/neofs-s3-gw/api.AttachUserAuth.func1.1({0x132b710, 0xc0549334a0}, 0xc054957300)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         github.com/nspcc-dev/neofs-s3-gw/api/user_auth.go:41 +0x5d4
Nov 07 14:08:05 az neofs-s3-gw[55804]: net/http.HandlerFunc.ServeHTTP(0x132cd28?, {0x132b710?, 0xc0549334a0?}, 0x1000000000000?)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         net/http/server.go:2084 +0x2f
Nov 07 14:08:05 az neofs-s3-gw[55804]: github.com/nspcc-dev/neofs-s3-gw/api.logErrorResponse.func1.1({0x132c490?, 0xc05147b960}, 0xc054957300)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         github.com/nspcc-dev/neofs-s3-gw/api/router.go:155 +0x104
Nov 07 14:08:05 az neofs-s3-gw[55804]: net/http.HandlerFunc.ServeHTTP(0xfff880?, {0x132c490?, 0xc05147b960?}, 0x2?)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         net/http/server.go:2084 +0x2f
Nov 07 14:08:05 az neofs-s3-gw[55804]: github.com/nspcc-dev/neofs-s3-gw/api.setRequestID.func1({0x132c490, 0xc05147b960}, 0xc054957100)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         github.com/nspcc-dev/neofs-s3-gw/api/router.go:135 +0x70e
Nov 07 14:08:05 az neofs-s3-gw[55804]: net/http.HandlerFunc.ServeHTTP(0xc0549f8000?, {0x132c490?, 0xc05147b960?}, 0xc00c709520?)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         net/http/server.go:2084 +0x2f
Nov 07 14:08:05 az neofs-s3-gw[55804]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc00039e840, {0x132c490, 0xc05147b960}, 0xc0547ae900)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
Nov 07 14:08:05 az neofs-s3-gw[55804]: net/http.serverHandler.ServeHTTP({0x132a1a0?}, {0x132c490, 0xc05147b960}, 0xc0547ae900)
Nov 07 14:08:05 az neofs-s3-gw[55804]:         net/http/server.go:2916 +0x43b
Nov 07 14:08:05 az neofs-s3-gw[55804]: net/http.(*conn).serve(0xc001cf7a40, {0x132cd28, 0xc0005a2210})
Nov 07 14:08:05 az neofs-s3-gw[55804]:         net/http/server.go:1966 +0x5d7
Nov 07 14:08:05 az neofs-s3-gw[55804]: created by net/http.(*Server).Serve
Nov 07 14:08:05 az neofs-s3-gw[55804]:         net/http/server.go:3071 +0x4db
Nov 07 14:08:05 az neofs-s3-gw[55804]: 2022-11-07T14:08:05.446Z        error        handler/util.go:29        call method        {"status": 500, "request_id": "261edce6-e39d-4828-aa76-ae7a6df89ae1", "method": "PutObject", "bucket": "d9d604f3-f44b-4082-bac1-c933569aaa97", "object": "be39f655-5ee4-439c-bb2f-424ab3a592a1", "description": "could not upload object", "error": "save object via connection pool: init call context: no healthy client", "body close errors": []}
Nov 07 14:08:05 az neofs-s3-gw[55804]: 2022-11-07T14:08:05.494Z        error        handler/util.go:29        call method        {"status": 500, "request_id": "7ff82ad3-50d1-4e4b-a973-cd47f4c179c8", "method": "PutObject", "bucket": "d9d604f3-f44b-4082-bac1-c933569aaa97", "object": "03f9f4df-4ab2-445f-8dea-3a6a62cd9671", "description": "could not upload object", "error": "save object via connection pool: init call context: no healthy client", "body close errors": []}
Nov 07 14:08:05 az neofs-s3-gw[55804]: 2022-11-07T14:08:05.549Z        error        handler/util.go:29        call method        {"status": 500, "request_id": "acd2cfbb-4874-412c-9eae-21183926b430", "method": "PutObject", "bucket": "d9d604f3-f44b-4082-bac1-c933569aaa97", "object": "b7b80c13-b3ab-41eb-8c34-90155a0f6751", "description": "could not upload object", "error": "save object via connection pool: init call context: no healthy client", "body close errors": []}
~
```

**Comment by alexvanin** [comment]
```go
	prm.Payload = wrapReader(prm.Payload, 64*1024, func(buf []byte) {
		hash.Write(buf)
	})
	id, err := n.neoFS.CreateObject(ctx, prm)
	return id, hash.Sum(nil), err
```

Consider returning `nil, nil, err` if `CreateObject` returns error. `hash.Sum(nil)` is not thread safe as it seems.

**Comment by alexvanin** [comment]
Closed in #752
