### ISSUE TITLE
Authmate throws NPE panic

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-s3-gw#794]
```
$ ./neofs-s3-authmate  issue-secret --wallet <...>  --peer <...>   --gate-public-key <...> --bearer-rules rules.json --aws-cli-credentials ~/.aws/credentials
Enter password for xk6-neofs/scenarios/files/wallet.json >
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa65b44]

goroutine 1 [running]:
github.com/nspcc-dev/neofs-api-go/v2/rpc/grpc.(*Client).Init(0x0, {{0xf555b5, 0x1e}, {0xf3fc90, 0xb}, 0x1}, {0xc000a2acd0, 0x1, 0xc0006580b0?})
        github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/rpc/grpc/init.go:81 +0x2e4
github.com/nspcc-dev/neofs-api-go/v2/rpc/client.(*Client).initGRPC(0xc00033c0c0, {{0xf555b5, 0x1e}, {0xf3fc90, 0xb}, 0x1}, 0xc0006580b0)
        github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/rpc/client/init.go:75 +0xf8
github.com/nspcc-dev/neofs-api-go/v2/rpc/client.(*Client).Init(0x7f9c714c5108?, {{0xf555b5, 0x1e}, {0xf3fc90, 0xb}, 0x1}, {0xc000a2aeb0, 0x1, 0x18?})
        github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/rpc/client/init.go:48 +0xfd
github.com/nspcc-dev/neofs-api-go/v2/rpc/client.SendUnary(0x46469a?, {{0xf555b5, 0x1e}, {0xf3fc90, 0xb}, 0x1}, {0x12a2c90, 0xc000010078}, {0x12a2d08, 0xc0000100d8}, ...)
        github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/rpc/client/flows.go:15 +0x8a
github.com/nspcc-dev/neofs-api-go/v2/rpc.NetworkInfo(0x8?, 0xe47e60?, {0xc000a2aeb0, 0x1, 0x1})
        github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/rpc/netmap.go:41 +0x126
github.com/nspcc-dev/neofs-sdk-go/client.(*Client).NetworkInfo.func1()
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9.0.20230606101007-79edfa63bbc9/client/netmap.go:142 +0x78
github.com/nspcc-dev/neofs-sdk-go/client.(*contextCall).processCall.func1()
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9.0.20230606101007-79edfa63bbc9/client/common.go:252 +0x25
github.com/nspcc-dev/neofs-sdk-go/client.(*contextCall).writeRequest(0xc00065c240)
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9.0.20230606101007-79edfa63bbc9/client/common.go:160 +0x187
github.com/nspcc-dev/neofs-sdk-go/client.(*contextCall).processCall(0xc00065c240)
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9.0.20230606101007-79edfa63bbc9/client/common.go:257 +0x85
github.com/nspcc-dev/neofs-sdk-go/client.(*Client).NetworkInfo(0xc00033c0a0, {0x12a81a8?, 0xc00033c000}, {{{0x0?, 0xe40ac0?, 0x19e2d00?}}})
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9.0.20230606101007-79edfa63bbc9/client/netmap.go:163 +0x247
github.com/nspcc-dev/neofs-sdk-go/pool.(*clientWrapper).networkInfo(0xc000000780, {0x12a81a8, 0xc00033c000}, {})
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9.0.20230606101007-79edfa63bbc9/pool/pool.go:566 +0x88
github.com/nspcc-dev/neofs-sdk-go/pool.initSessionForDuration({0x12a81a8, 0xc00033c000}, 0xc000a2b6d0, {0x12b5ca0, 0xc000000780}, 0x64, {0x12a7d00, 0xc0006502d0})
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9.0.20230606101007-79edfa63bbc9/pool/pool.go:1726 +0x7e
github.com/nspcc-dev/neofs-sdk-go/pool.(*Pool).Dial(0xc00065c120, {0x12a81a8, 0xc00033c000})
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9.0.20230606101007-79edfa63bbc9/pool/pool.go:1475 +0x9ec
main.createNeoFS({0x12a81a8, 0xc00033c000}, 0xc0004935e0?, {0xc000650210, {0x7ffe778ae5b7, 0x27}, 0x12a05f200, 0x12a05f200, 0x2540be400, 0x6fc23ac00})
        github.com/nspcc-dev/neofs-s3-gw/cmd/s3-authmate/main.go:703 +0x265
main.issueSecret.func1(0xc000ae6000?)
        github.com/nspcc-dev/neofs-s3-gw/cmd/s3-authmate/main.go:317 +0x2b2
github.com/urfave/cli/v2.(*Command).Run(0xc00049afc0, 0xc0004b5ec0)
        github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5c8
github.com/urfave/cli/v2.(*App).RunContext(0xc0004836c0, {0x12a81e0?, 0xc000324010}, {0xc000338000, 0xc, 0xc})
        github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb36
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        github.com/nspcc-dev/neofs-s3-gw/cmd/s3-authmate/main.go:147 +0x425
```

### Version
```
$ ./neofs-s3-authmate --version
NeoFS S3 Authmate
Version: v0.27.1
GoVersion: go1.20.4
```

**Comment by cthulhu-rider** [comment]
the problem may be fixed by upgrading to https://github.com/nspcc-dev/neofs-sdk-go/commit/79d4b97db942e9165f1d5aabe83b62fbed03eba7

**Comment by roman-khimov** [comment]
Seems to be fixed now.
